"""
Django settings for loadtesting project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '--6sr^m&!m(+0brlzt(t-9kavr(u9hwow+sts=+9+3x7)jx0rg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'swampdragon',
    'frontend',
    'backend'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'loadtesting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loadtesting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '%s/static/'%BASE_DIR

CELERY_ALWAYS_EAGER = False

FRONTEND_DEFAULT_SETTINGS = {
    'jmeter':{
        'ami_id': 'ami-bb1e79cc',
        'url': 'https://xlab.koofr.net/content/links/2338100d-d4c2-4402-823b-aa83e0092b39/files/get/jmeter_master.tar.gz?path=',
        'key_name' : 'distributedjmeter',
    },
    'db':{
        'master_identifier': 'cloudscale-master',
        'replica_identifier': 'cloudscale-replica',
        'username': 'root',
        'password': 'password',
        'name': 'tpcw',
        'url': 'http://cloudscale.xlab.si/showcase/dumps/rds-tpcw-dump-latest.sql'
    },
    'fr':{
        'dist_url': 'http://cloudscale.xlab.si/showcase/builds/showcaseV3-sql.war',
        'autoscaling' : 'no',
        'cooldown': 300,
        'ami_id': 'ami-bb1e79cc',
        'region': 'eu-west-1',
        'availability_zone': 'eu-west-1a',
        'keyname': 'cloudscale',
        'remote_user': 'ubuntu',
        'instance_identifier': 'cloudscale'
    }
}

# SwampDragon configurations
SWAMP_DRAGON_CONNECTION = ('swampdragon.connections.sockjs_connection.DjangoSubscriberConnection', '/data')
DRAGON_URL = 'http://localhost:9999/'